version: '3.8'

services:

  mysql:
    image: mysql:8.0.33
    platform: linux/amd64
    container_name: ruty-mysql
    restart: always
    ports:
      - 3307:3306 # 배포된 환경에서는 3306:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: song
      MYSQL_PASSWORD: 1234
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - testnet
  redis:
    container_name: ruty-redis
    image: redis
    ports:
      - 6379:6379
    restart: always
    networks:
      - testnet

  backend:
    container_name: ruty-server
    image: singsangssong/cicd-practice
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - mysql
      - redis
    networks:
      - testnet

networks:
  testnet:
    driver: bridge
